apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: gcr.io/capable-memory-409516/mynodeapp@sha256:0892a523d38f67fb67cef0427dfb695c0aff00b317313fc369966abeee447efa
        ports:
        - containerPort: 3000
