# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      run: |
        echo "$GCP_SERVICE_KEY" > /tmp/gcp_key.json &&
        gcloud auth activate-service-account --key-file=/tmp/gcp_key.json &&
        gcloud auth configure-docker &&
        gcloud config set project $GCP_PROJECT_ID
        
      env:
        GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    - name: Build and push Docker image to GCR
      run: |
        IMAGE_URL=gcr.io/$GCP_PROJECT_ID/your-image-name:$GITHUB_SHA
        docker build -t $IMAGE_URL .
        docker push $IMAGE_URL
        echo "Docker image URL: $IMAGE_URL" >> image_url.txt

    - name: Deploy to GKE
      run: |
        # Create GKE cluster with minimum vCPUs and SSD_TOTAL_GB
        gcloud container clusters create k8s-testing \
          --region=us-central1 \
          --num-nodes=1 \
          --machine-type=e2-micro
    
        gcloud container clusters get-credentials k8s-testing --region=us-central1
    
        # Get the Docker image URL from the file
        IMAGE_URL=$(cat image_url.txt)
    
        # Replace the image URL in the deployment file
        sed -i "s|us-central1-docker.pkg.dev/capable-memory-409516/hello-repo/hello-app:v2|$IMAGE_URL|" deployment.yaml
    
        kubectl apply -f deployment.yaml
      
    env:
      GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
