# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      run: |
        gcloud auth activate-service-account --key-file="$GCP_SERVICE_KEY" &&
        gcloud auth configure-docker &&
        gcloud config set project $GCP_PROJECT_ID
      env:
        GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        
    - name: Build and push Docker image to GCR
      run: |
        docker build -t gcr.io/$GCP_PROJECT_ID/your-image-name:$GITHUB_SHA .
        docker push gcr.io/$GCP_PROJECT_ID/your-image-name:$GITHUB_SHA

      env:
        GCP_SERVICE_KEY: ${{ secrets.GCP_SERVICE_KEY }}
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    - name: Deploy to GKE
      run: |
        gcloud container clusters get-credentials k8s-testing --region us-central1
        kubectl apply -f your-deployment-file.yaml
